// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: clairvoyant_meta.proto

package clairvoyantmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Segment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegmentId    string   `protobuf:"bytes,1,opt,name=segmentId,proto3" json:"segmentId,omitempty"`
	Popularity   float64  `protobuf:"fixed64,2,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Size         int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	LastAccessed int64    `protobuf:"varint,4,opt,name=lastAccessed,proto3" json:"lastAccessed,omitempty"`
	NodeIds      []string `protobuf:"bytes,5,rep,name=nodeIds,proto3" json:"nodeIds,omitempty"`
}

func (x *Segment) Reset() {
	*x = Segment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *Segment) GetPopularity() float64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *Segment) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Segment) GetLastAccessed() int64 {
	if x != nil {
		return x.LastAccessed
	}
	return 0
}

func (x *Segment) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId  string     `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
	Segments []*Segment `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{1}
}

func (x *Video) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Video) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Position) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId     string    `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Address    string    `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	NodePos    *Position `protobuf:"bytes,3,opt,name=node_pos,json=nodePos,proto3" json:"node_pos,omitempty"`
	UserPosIdx int64     `protobuf:"varint,4,opt,name=user_pos_idx,json=userPosIdx,proto3" json:"user_pos_idx,omitempty"`
	Distance   float64   `protobuf:"fixed64,5,opt,name=distance,proto3" json:"distance,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{3}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetNodePos() *Position {
	if x != nil {
		return x.NodePos
	}
	return nil
}

func (x *NodeInfo) GetUserPosIdx() int64 {
	if x != nil {
		return x.UserPosIdx
	}
	return 0
}

func (x *NodeInfo) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type NodeSegments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId     string   `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	SegmentIds []string `protobuf:"bytes,2,rep,name=segmentIds,proto3" json:"segmentIds,omitempty"`
}

func (x *NodeSegments) Reset() {
	*x = NodeSegments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeSegments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSegments) ProtoMessage() {}

func (x *NodeSegments) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSegments.ProtoReflect.Descriptor instead.
func (*NodeSegments) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{4}
}

func (x *NodeSegments) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeSegments) GetSegmentIds() []string {
	if x != nil {
		return x.SegmentIds
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteId    string          `protobuf:"bytes,1,opt,name=routeId,proto3" json:"routeId,omitempty"`
	Placements []*NodeSegments `protobuf:"bytes,2,rep,name=placements,proto3" json:"placements,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{5}
}

func (x *Route) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Route) GetPlacements() []*NodeSegments {
	if x != nil {
		return x.Placements
	}
	return nil
}

type GetVideoInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId string `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
}

func (x *GetVideoInfoRequest) Reset() {
	*x = GetVideoInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoRequest) ProtoMessage() {}

func (x *GetVideoInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoInfoRequest) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideoInfoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetVideoInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Video *Video `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
}

func (x *GetVideoInfoResponse) Reset() {
	*x = GetVideoInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoResponse) ProtoMessage() {}

func (x *GetVideoInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoResponse.ProtoReflect.Descriptor instead.
func (*GetVideoInfoResponse) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideoInfoResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type GetNearestNodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Positions []*Position `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *GetNearestNodesRequest) Reset() {
	*x = GetNearestNodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearestNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearestNodesRequest) ProtoMessage() {}

func (x *GetNearestNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearestNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNearestNodesRequest) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{8}
}

func (x *GetNearestNodesRequest) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type GetNearestNodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeInfo `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *GetNearestNodesResponse) Reset() {
	*x = GetNearestNodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearestNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearestNodesResponse) ProtoMessage() {}

func (x *GetNearestNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearestNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNearestNodesResponse) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{9}
}

func (x *GetNearestNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SegmentOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Segment   *Segment `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
}

func (x *SegmentOperation) Reset() {
	*x = SegmentOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentOperation) ProtoMessage() {}

func (x *SegmentOperation) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentOperation.ProtoReflect.Descriptor instead.
func (*SegmentOperation) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{10}
}

func (x *SegmentOperation) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *SegmentOperation) GetSegment() *Segment {
	if x != nil {
		return x.Segment
	}
	return nil
}

type UpdateSegmentInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegmentOperations []*SegmentOperation `protobuf:"bytes,1,rep,name=segmentOperations,proto3" json:"segmentOperations,omitempty"`
}

func (x *UpdateSegmentInfoRequest) Reset() {
	*x = UpdateSegmentInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSegmentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSegmentInfoRequest) ProtoMessage() {}

func (x *UpdateSegmentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSegmentInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateSegmentInfoRequest) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSegmentInfoRequest) GetSegmentOperations() []*SegmentOperation {
	if x != nil {
		return x.SegmentOperations
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statuses []string `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type AddVideoInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*Video `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *AddVideoInfoRequest) Reset() {
	*x = AddVideoInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVideoInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideoInfoRequest) ProtoMessage() {}

func (x *AddVideoInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideoInfoRequest.ProtoReflect.Descriptor instead.
func (*AddVideoInfoRequest) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{13}
}

func (x *AddVideoInfoRequest) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type AddRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteId string `protobuf:"bytes,1,opt,name=routeId,proto3" json:"routeId,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddRouteRequest) Reset() {
	*x = AddRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteRequest) ProtoMessage() {}

func (x *AddRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteRequest.ProtoReflect.Descriptor instead.
func (*AddRouteRequest) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{14}
}

func (x *AddRouteRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *AddRouteRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteId string `protobuf:"bytes,1,opt,name=routeId,proto3" json:"routeId,omitempty"`
}

func (x *DeleteRouteRequest) Reset() {
	*x = DeleteRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteRequest) ProtoMessage() {}

func (x *DeleteRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRouteRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type GetRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteId string `protobuf:"bytes,1,opt,name=routeId,proto3" json:"routeId,omitempty"`
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{16}
}

func (x *GetRouteRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*Request_GetVideoInfoRequest
	//	*Request_GetNearestNodesRequest
	//	*Request_UpdateSegmentInfoRequest
	//	*Request_AddVideoInfoRequest
	//	*Request_AddRouteRequest
	//	*Request_DeleteRouteRequest
	//	*Request_GetRouteRequest
	Request isRequest_Request `protobuf_oneof:"request"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{17}
}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *Request) GetGetVideoInfoRequest() *GetVideoInfoRequest {
	if x, ok := x.GetRequest().(*Request_GetVideoInfoRequest); ok {
		return x.GetVideoInfoRequest
	}
	return nil
}

func (x *Request) GetGetNearestNodesRequest() *GetNearestNodesRequest {
	if x, ok := x.GetRequest().(*Request_GetNearestNodesRequest); ok {
		return x.GetNearestNodesRequest
	}
	return nil
}

func (x *Request) GetUpdateSegmentInfoRequest() *UpdateSegmentInfoRequest {
	if x, ok := x.GetRequest().(*Request_UpdateSegmentInfoRequest); ok {
		return x.UpdateSegmentInfoRequest
	}
	return nil
}

func (x *Request) GetAddVideoInfoRequest() *AddVideoInfoRequest {
	if x, ok := x.GetRequest().(*Request_AddVideoInfoRequest); ok {
		return x.AddVideoInfoRequest
	}
	return nil
}

func (x *Request) GetAddRouteRequest() *AddRouteRequest {
	if x, ok := x.GetRequest().(*Request_AddRouteRequest); ok {
		return x.AddRouteRequest
	}
	return nil
}

func (x *Request) GetDeleteRouteRequest() *DeleteRouteRequest {
	if x, ok := x.GetRequest().(*Request_DeleteRouteRequest); ok {
		return x.DeleteRouteRequest
	}
	return nil
}

func (x *Request) GetGetRouteRequest() *GetRouteRequest {
	if x, ok := x.GetRequest().(*Request_GetRouteRequest); ok {
		return x.GetRouteRequest
	}
	return nil
}

type isRequest_Request interface {
	isRequest_Request()
}

type Request_GetVideoInfoRequest struct {
	GetVideoInfoRequest *GetVideoInfoRequest `protobuf:"bytes,1,opt,name=getVideoInfoRequest,proto3,oneof"`
}

type Request_GetNearestNodesRequest struct {
	GetNearestNodesRequest *GetNearestNodesRequest `protobuf:"bytes,2,opt,name=getNearestNodesRequest,proto3,oneof"`
}

type Request_UpdateSegmentInfoRequest struct {
	UpdateSegmentInfoRequest *UpdateSegmentInfoRequest `protobuf:"bytes,3,opt,name=updateSegmentInfoRequest,proto3,oneof"`
}

type Request_AddVideoInfoRequest struct {
	AddVideoInfoRequest *AddVideoInfoRequest `protobuf:"bytes,4,opt,name=addVideoInfoRequest,proto3,oneof"`
}

type Request_AddRouteRequest struct {
	AddRouteRequest *AddRouteRequest `protobuf:"bytes,5,opt,name=addRouteRequest,proto3,oneof"`
}

type Request_DeleteRouteRequest struct {
	DeleteRouteRequest *DeleteRouteRequest `protobuf:"bytes,6,opt,name=deleteRouteRequest,proto3,oneof"`
}

type Request_GetRouteRequest struct {
	GetRouteRequest *GetRouteRequest `protobuf:"bytes,7,opt,name=getRouteRequest,proto3,oneof"`
}

func (*Request_GetVideoInfoRequest) isRequest_Request() {}

func (*Request_GetNearestNodesRequest) isRequest_Request() {}

func (*Request_UpdateSegmentInfoRequest) isRequest_Request() {}

func (*Request_AddVideoInfoRequest) isRequest_Request() {}

func (*Request_AddRouteRequest) isRequest_Request() {}

func (*Request_DeleteRouteRequest) isRequest_Request() {}

func (*Request_GetRouteRequest) isRequest_Request() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*Response_GetVideoInfoResponse
	//	*Response_GetNearestNodesResponse
	//	*Response_StatusResponse
	Response isResponse_Response `protobuf_oneof:"response"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_meta_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_meta_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_clairvoyant_meta_proto_rawDescGZIP(), []int{18}
}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *Response) GetGetVideoInfoResponse() *GetVideoInfoResponse {
	if x, ok := x.GetResponse().(*Response_GetVideoInfoResponse); ok {
		return x.GetVideoInfoResponse
	}
	return nil
}

func (x *Response) GetGetNearestNodesResponse() *GetNearestNodesResponse {
	if x, ok := x.GetResponse().(*Response_GetNearestNodesResponse); ok {
		return x.GetNearestNodesResponse
	}
	return nil
}

func (x *Response) GetStatusResponse() *StatusResponse {
	if x, ok := x.GetResponse().(*Response_StatusResponse); ok {
		return x.StatusResponse
	}
	return nil
}

type isResponse_Response interface {
	isResponse_Response()
}

type Response_GetVideoInfoResponse struct {
	GetVideoInfoResponse *GetVideoInfoResponse `protobuf:"bytes,1,opt,name=getVideoInfoResponse,proto3,oneof"`
}

type Response_GetNearestNodesResponse struct {
	GetNearestNodesResponse *GetNearestNodesResponse `protobuf:"bytes,2,opt,name=getNearestNodesResponse,proto3,oneof"`
}

type Response_StatusResponse struct {
	StatusResponse *StatusResponse `protobuf:"bytes,3,opt,name=statusResponse,proto3,oneof"`
}

func (*Response_GetVideoInfoResponse) isResponse_Response() {}

func (*Response_GetNearestNodesResponse) isResponse_Response() {}

func (*Response_StatusResponse) isResponse_Response() {}

var File_clairvoyant_meta_proto protoreflect.FileDescriptor

var file_clairvoyant_meta_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x5f, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76,
	0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x99, 0x01, 0x0a, 0x07, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c,
	0x61, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x73, 0x22, 0x57, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x61,
	0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x44,
	0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x34, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79,
	0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x70, 0x6f, 0x73, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x49, 0x64, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x46, 0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22,
	0x60, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f,
	0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x2f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x49, 0x64, 0x22, 0x44, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x61, 0x69,
	0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x22, 0x51, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4e,
	0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79,
	0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79,
	0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x64, 0x0a, 0x10, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x07, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x61,
	0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x6b, 0x0a,
	0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x11, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61,
	0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2c, 0x0a, 0x0e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2e, 0x0a, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x22,
	0x43, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x2e, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49,
	0x64, 0x22, 0x87, 0x05, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x58, 0x0a,
	0x13, 0x67, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6c, 0x61,
	0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x13, 0x67, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x61, 0x0a, 0x16, 0x67, 0x65, 0x74, 0x4e, 0x65,
	0x61, 0x72, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76,
	0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61,
	0x72, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x16, 0x67, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x67, 0x0a, 0x18, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63,
	0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x18, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x58, 0x0a, 0x13, 0x61, 0x64, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x13, 0x61, 0x64, 0x64, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a,
	0x0f, 0x61, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f,
	0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x61, 0x64, 0x64, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x55, 0x0a, 0x12, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76,
	0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x12,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x4c, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6c,
	0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0f, 0x67, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa4, 0x02, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f,
	0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x14, 0x67, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x17, 0x67, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72,
	0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f,
	0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72,
	0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x17, 0x67, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0e, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e,
	0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x58, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0d, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79,
	0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x45, 0x5a, 0x43,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x65, 0x64,
	0x75, 0x2f, 0x63, 0x73, 0x2d, 0x65, 0x70, 0x6c, 0x2f, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f,
	0x79, 0x61, 0x6e, 0x74, 0x32, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x67, 0x6f, 0x2f, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x6d,
	0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clairvoyant_meta_proto_rawDescOnce sync.Once
	file_clairvoyant_meta_proto_rawDescData = file_clairvoyant_meta_proto_rawDesc
)

func file_clairvoyant_meta_proto_rawDescGZIP() []byte {
	file_clairvoyant_meta_proto_rawDescOnce.Do(func() {
		file_clairvoyant_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_clairvoyant_meta_proto_rawDescData)
	})
	return file_clairvoyant_meta_proto_rawDescData
}

var file_clairvoyant_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_clairvoyant_meta_proto_goTypes = []interface{}{
	(*Segment)(nil),                  // 0: clairvoyantmeta.Segment
	(*Video)(nil),                    // 1: clairvoyantmeta.Video
	(*Position)(nil),                 // 2: clairvoyantmeta.Position
	(*NodeInfo)(nil),                 // 3: clairvoyantmeta.NodeInfo
	(*NodeSegments)(nil),             // 4: clairvoyantmeta.NodeSegments
	(*Route)(nil),                    // 5: clairvoyantmeta.Route
	(*GetVideoInfoRequest)(nil),      // 6: clairvoyantmeta.GetVideoInfoRequest
	(*GetVideoInfoResponse)(nil),     // 7: clairvoyantmeta.GetVideoInfoResponse
	(*GetNearestNodesRequest)(nil),   // 8: clairvoyantmeta.GetNearestNodesRequest
	(*GetNearestNodesResponse)(nil),  // 9: clairvoyantmeta.GetNearestNodesResponse
	(*SegmentOperation)(nil),         // 10: clairvoyantmeta.SegmentOperation
	(*UpdateSegmentInfoRequest)(nil), // 11: clairvoyantmeta.UpdateSegmentInfoRequest
	(*StatusResponse)(nil),           // 12: clairvoyantmeta.StatusResponse
	(*AddVideoInfoRequest)(nil),      // 13: clairvoyantmeta.AddVideoInfoRequest
	(*AddRouteRequest)(nil),          // 14: clairvoyantmeta.AddRouteRequest
	(*DeleteRouteRequest)(nil),       // 15: clairvoyantmeta.DeleteRouteRequest
	(*GetRouteRequest)(nil),          // 16: clairvoyantmeta.GetRouteRequest
	(*Request)(nil),                  // 17: clairvoyantmeta.Request
	(*Response)(nil),                 // 18: clairvoyantmeta.Response
}
var file_clairvoyant_meta_proto_depIdxs = []int32{
	0,  // 0: clairvoyantmeta.Video.segments:type_name -> clairvoyantmeta.Segment
	2,  // 1: clairvoyantmeta.NodeInfo.node_pos:type_name -> clairvoyantmeta.Position
	4,  // 2: clairvoyantmeta.Route.placements:type_name -> clairvoyantmeta.NodeSegments
	1,  // 3: clairvoyantmeta.GetVideoInfoResponse.video:type_name -> clairvoyantmeta.Video
	2,  // 4: clairvoyantmeta.GetNearestNodesRequest.positions:type_name -> clairvoyantmeta.Position
	3,  // 5: clairvoyantmeta.GetNearestNodesResponse.nodes:type_name -> clairvoyantmeta.NodeInfo
	0,  // 6: clairvoyantmeta.SegmentOperation.segment:type_name -> clairvoyantmeta.Segment
	10, // 7: clairvoyantmeta.UpdateSegmentInfoRequest.segmentOperations:type_name -> clairvoyantmeta.SegmentOperation
	1,  // 8: clairvoyantmeta.AddVideoInfoRequest.videos:type_name -> clairvoyantmeta.Video
	6,  // 9: clairvoyantmeta.Request.getVideoInfoRequest:type_name -> clairvoyantmeta.GetVideoInfoRequest
	8,  // 10: clairvoyantmeta.Request.getNearestNodesRequest:type_name -> clairvoyantmeta.GetNearestNodesRequest
	11, // 11: clairvoyantmeta.Request.updateSegmentInfoRequest:type_name -> clairvoyantmeta.UpdateSegmentInfoRequest
	13, // 12: clairvoyantmeta.Request.addVideoInfoRequest:type_name -> clairvoyantmeta.AddVideoInfoRequest
	14, // 13: clairvoyantmeta.Request.addRouteRequest:type_name -> clairvoyantmeta.AddRouteRequest
	15, // 14: clairvoyantmeta.Request.deleteRouteRequest:type_name -> clairvoyantmeta.DeleteRouteRequest
	16, // 15: clairvoyantmeta.Request.getRouteRequest:type_name -> clairvoyantmeta.GetRouteRequest
	7,  // 16: clairvoyantmeta.Response.getVideoInfoResponse:type_name -> clairvoyantmeta.GetVideoInfoResponse
	9,  // 17: clairvoyantmeta.Response.getNearestNodesResponse:type_name -> clairvoyantmeta.GetNearestNodesResponse
	12, // 18: clairvoyantmeta.Response.statusResponse:type_name -> clairvoyantmeta.StatusResponse
	17, // 19: clairvoyantmeta.MetadataServer.handleRequest:input_type -> clairvoyantmeta.Request
	18, // 20: clairvoyantmeta.MetadataServer.handleRequest:output_type -> clairvoyantmeta.Response
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_clairvoyant_meta_proto_init() }
func file_clairvoyant_meta_proto_init() {
	if File_clairvoyant_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clairvoyant_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeSegments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearestNodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearestNodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSegmentInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVideoInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clairvoyant_meta_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_clairvoyant_meta_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*Request_GetVideoInfoRequest)(nil),
		(*Request_GetNearestNodesRequest)(nil),
		(*Request_UpdateSegmentInfoRequest)(nil),
		(*Request_AddVideoInfoRequest)(nil),
		(*Request_AddRouteRequest)(nil),
		(*Request_DeleteRouteRequest)(nil),
		(*Request_GetRouteRequest)(nil),
	}
	file_clairvoyant_meta_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*Response_GetVideoInfoResponse)(nil),
		(*Response_GetNearestNodesResponse)(nil),
		(*Response_StatusResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clairvoyant_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clairvoyant_meta_proto_goTypes,
		DependencyIndexes: file_clairvoyant_meta_proto_depIdxs,
		MessageInfos:      file_clairvoyant_meta_proto_msgTypes,
	}.Build()
	File_clairvoyant_meta_proto = out.File
	file_clairvoyant_meta_proto_rawDesc = nil
	file_clairvoyant_meta_proto_goTypes = nil
	file_clairvoyant_meta_proto_depIdxs = nil
}
